updated stafftime view and model
babybunny/rebuildingtogethercaptain pull request #312
Opened 2017-09-02 18:04 UTC by kate-mills

I made a small update to our stafftime view to test a pull request.

2017-09-04 03:06 UTC, babybunny requested changes
Do you have a demo version?  It's a good practice to create one and share the URL so I (as reviewer) can see the effect of the changes.

2017-09-04 03:06 UTC, babybunny commented on room/templates/stafftime_static.html
> -    {{ entity.description|escape|replace('\n', '<br>\n') }}
We do have to worry about HTML escaping in these templates.  For example what if someone enters a description like "I am full of mischief <script> ... do something terrible .."

See this about the autoescaping in jinja2.   
 http://jinja.pocoo.org/docs/2.9/api/#autoescaping

I'm not sure if it's enabled.  It probably should be.

2017-09-04 23:57 UTC, kate-mills commented
I created a demo version at https://kate-testing-dot-rebuildingtogethercaptain-hrd.appspot.com

2017-09-05 02:52 UTC, babybunny approved these changes
Looks good!

2017-09-05 02:53 UTC, merged