update import_csv and add test coverage for it
babybunny/rebuildingtogethercaptain pull request #456
Opened 2018-02-17 23:03 UTC by andy-d

2018-02-17 23:30 UTC, babybunny requested changes

2018-02-17 23:30 UTC, babybunny commented on import_csv.py
> +  program, created = ndb_models.Program.get_or_create(nrd_type.key, int(year))
minor: already asserted year is int

2018-02-17 23:30 UTC, babybunny commented on import_csv.py
> +  Change input_csv to actual input file - the default is test data.
no default anymore.

2018-02-17 23:30 UTC, babybunny commented on import_csv.py
> +    site.program = get_program(nrd_program_year).name
don't you need to set program_key?

2018-02-17 23:30 UTC, babybunny commented on import_csv.py
> +    budget = s.get("Budgeted Cost in Campaign", "$0").strip("$").replace(",", "") or '0'
way better, thanks

2018-02-17 23:30 UTC, babybunny commented on import_csv.py
> +  Change input_csv to actual input file - the default is test data.
no default here

2018-02-17 23:30 UTC, babybunny commented on import_csv.py
> +      captain = ndb_models.Captain.query().filter(ndb_models.Captain.email == email).get()
Here and in other places, can put  the filter param directly into query(). 

Like 
ndb_models.Captain.query(ndb_models.Captain.email == email)

see https://cloud.google.com/appengine/docs/standard/python/ndb/queries

2018-02-17 23:30 UTC, babybunny commented on test/test_import_csv.py
> +        self.assertEqual(captain.email, 'mike@nibbi.com')
Let's avoid putting real email addresses in github.

2018-02-17 23:30 UTC, babybunny commented on test/test_import_csv.py
> +subject of announcement,"announcement body, has some commas",18001DAL,"$10,000",Man Shu Lau,,(415) 350-7499,,221 South Hill Court,Daly City,94014,Daly City,Woodlawn Foundation & St. Andrews Church (v
also here, real data is not appropriate. let's invent some made-up world based on Tiago's imagination.

2018-02-18 00:40 UTC, andy-d commented
Ack I’ll sanitize test data and update based on feedback thanks

2018-02-18 02:57 UTC, closed without merging

2018-02-18 02:59 UTC, andy-d commented
Removed the previous commit to avoid private data leakage